### ISSUE TITLE
how to close a connection from the server side?

### ISSUE THREAD

**Issue by lasiotus** [lowlevl/assh#1] opened 2024-06-07 03:24 UTC
Hello!

I'm hacking https://github.com/lowlevl/assh/blob/main/examples/examples/server.rs; I replaced

```rust
for frame in FRAMES.iter().cycle() {
    writer.write_all(CLEAR.as_bytes()).await?;
    writer.write_all(frame.as_bytes()).await?;
    writer.flush().await?;

    tokio::time::sleep(DELAY).await;
}

Ok::<_, eyre::Error>(())
```

with 

```rust
writer.write_all("hello! type something; 'q' to quit".as_bytes()).await?;
writer.flush().await?;

let mut reader = channel.as_reader();
loop {
    let mut buf = [0_u8; 64];
    let r = reader.read(&mut buf).await?;
    writer.write(&buf[0..r]).await?;
    writer.flush().await?;

    if r == 1 && buf[0] == b'q' {
        break;
    }
}

writer.write("\n\ndone\n\n".as_bytes()).await?;
writer.flush().await?;
// TODO: how do I close the channel here?

Ok::<_, eyre::Error>(())
```

How do I close the channel at the point where ```// TODO``` is above? As is, the client session `ssh -p 2222 localhost` just hangs after ```done``` is printed...

**Comment by lowlevl** [comment] 2024-06-07 13:14
Hi there,

Thanks for you issue, good catch, it looks like this is not supported by the project _yet_, I've just committed d9fb11b052b8aebf26a489a23ee74924d938aa47 to be able to reproduce the issue and indeed the client hangs, because while dropping the channel closes it locally, it does not communicate this to the peer.

I'll take a look at the issue soon to make this work. In my design idea, the channel getting out of scope should communicate closing to the peer, so nothing would need to be added to your code for it to work.

**Comment by lowlevl** [comment] 2024-06-07 13:54
Update: With e1973b4fd3616d6a72b5930bae3a62b83368935c pushed you might try again, this should close the channel as intended.

**Closed by lowlevl** 2024-06-07 13:54 UTC

**Comment by lasiotus** [comment] 2024-06-07 15:31
Thank you! Yours is the nicest ssh protocol implementation in Rust I've seen (assh, russh, sunset, thrussh). Now I only need to port tokio to my OS project to use assh... :)

**Comment by lowlevl** [comment] 2024-06-07 15:41
You're welcome, thanks for the cheers up :)
I still consider the project unfinished since there are many _`TODO:`_ still in the code (see https://github.com/search?q=repo%3Alowlevl%2Fassh%20TODO%3A&type=code), and the code isn't widely tested yet.
So use it with caution as the crates may be unsafe in a protocol's safety stand point.

Also the crate is designed to be working with any async crate (I haven't tested it though), so you might want to try `smol` (https://docs.rs/smol) instead if you're going small :)

**Comment by lasiotus** [comment] 2024-06-07 15:53
Oh, you don't directly depend on Tokio - then it is very easy - I have a working async executor (single-threaded) lying around somewhere. Or maybe smol will just compile with minimal tweaks (or none at all).

Re: assh being unfinished: my [OS](https://github.com/moturus/motor-os) is much more unfinished, but now that it has a decent TCP/networking stack it needs an sshd, at it looks like it will be based on assh. :)

**Comment by lowlevl** [comment] 2024-06-07 16:06
> you don't directly depend on Tokio

Yes, the crate only depends to any I/O that implements `futures::{AsyncWrite, AsyncBufRead}` so it should work either without a itch, or with [`async-compat`](https://docs.rs/async-compat) :)
It would be a huge thing if it worked on your homebrewed async executor !

> it looks like it will be based on assh

Great news, happy to see my work is useful to someone else !
